package com.jk.room_kotlin.data

// androidx - jetpack library
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

// Entity
@Entity(tableName = "table_notes")
class Note(
    val title: String,
    val description: String,
    val priority: Int,
    /*
    use  @ColumnInfo if you need to have different names for table column and class variable
     */
    // when you want to specify different name for var or object
//    @ColumnInfo(name = "completed") val markAsDone: Boolean,
    ) {

    @PrimaryKey(autoGenerate = true)
    var id = 0

//   This can't be autogenerated
//    @PrimaryKey
//    var userEmail : String = ""

    override fun toString(): String {
        return "Note(title='$title', description='$description', priority=$priority, id=$id)"
    }
}
